{
 "title": "cloud-devops-lab — Service Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cloud-devops-lab-app\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Uptime (seconds)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_uptime_seconds", "legendFormat": "uptime" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Request Rate (per second)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}